version: '3.8'

services:
  ytd:
    build: .
    command: >
      sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./YouTubeAudio/:/code/YouTubeAudio/
      - static_volume:/home/deploy/ytd/staticfiles
      - media_volume:/home/deploy/ytd/uploads/audio
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/db/lib/postgresql/data/
    env_file:
      - .env.db
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A YouTubeAudio worker -P gevent -l info && celery -A YouTubeAudio beat -l info
    volumes:
      - static_volume:/home/deploy/ytd/staticfiles
      - media_volume:/home/deploy/ytd/uploads/audio
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
      - ytd
volumes:
  postgres_data:
  static_volume:
  media_volume:
