DJANGO_SECRET_KEY="tv9c+y$bq!jp8sntizm9q#!_di*hvdj!uo4ofv19bi_r0o(zwy"
DJANGO_APP_HOST="mp3-from-youtube.com"
DJANGO_DB_ENGINE="django.db.backends.postgresql_psycopg2"
DJANGO_DB_NAME="ytd_psql"
DJANGO_DB_USER="postgres_ytd"
DJANGO_DB_PASSWORD="PuKAxU9JdZiwQrS"
DJANGO_DB_HOST="ytd-psql-database.cdsd46cwkcjl.ap-south-1.rds.amazonaws.com"
DJANGO_EMAIL_HOST_USER="sweet@ha.ha"
DJANGO_EMAIL_HOST_PASSWORD=""

