# Generated by Django 4.0.4 on 2022-06-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=255, verbose_name='URL to Youtube')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Video title')),
                ('audio_url', models.CharField(blank=True, max_length=255, verbose_name='URL to created audio')),
                ('pub_time', models.TimeField(blank=True, null=True, verbose_name='Publish time')),
                ('slug', models.SlugField(blank=True, default=' ')),
            ],
        ),
    ]
