# Generated by Django 4.0.4 on 2022-06-27 12:15

import audio.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='expiration_time',
            field=models.DateTimeField(default=audio.service.get_expiration_date, verbose_name='Burn time'),
        ),
    ]
