# Generated by Django 4.0.4 on 2022-06-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversion',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='pub_time',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='conversion',
            name='title',
        ),
    ]
