# Generated by Django 4.0.4 on 2022-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_alter_conversion_expiration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=256)),
                ('confirmation_code', models.CharField(max_length=4)),
            ],
        ),
    ]
