# Generated by Django 4.0.4 on 2022-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_conversion_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='pub_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Publish time'),
        ),
    ]
