# Generated by Django 4.0.4 on 2022-08-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0004_silentlist_confirmed_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silentlist',
            name='confirmed_email',
            field=models.EmailField(default='', max_length=256),
        ),
    ]
