# Generated by Django 4.0.6 on 2023-02-26 14:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0005_alter_silentlist_confirmed_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='silentlist',
            name='input_code',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='conversion',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 27, 14, 11, 36, 744164, tzinfo=utc), verbose_name='Burn time'),
        ),
    ]
