# Generated by Django 4.0.4 on 2022-06-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_conversion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='slug',
            field=models.SlugField(blank=True, default=' ', max_length=255),
        ),
    ]
