# Generated by Django 4.0.4 on 2022-06-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0007_alter_conversion_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversion',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='uploads/audio'),
        ),
        migrations.AddField(
            model_name='conversion',
            name='video_id',
            field=models.CharField(default='', max_length=100, verbose_name='ID video'),
        ),
    ]
