# Generated by Django 4.0.4 on 2022-06-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_conversion_audio_file_conversion_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversion',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio'),
        ),
    ]
